In [1]:
import numpy as np
import pandas as pd

In [2]:

dfR= pd.read_csv('/home/gsociety/Desktop/The Model/STORAGE/resultDataRR.csv')

In [3]:

dfR.head()

dfR['TEAMS']=pd.Series([x.upper() for x in dfR.TEAMS])

#split TEAMS into HOME & AWAY 
#df['HOME']=pd.Series([x.split()[1] for x in df.TEAMS])
#df['AWAY']=pd.Series([x.split()[3] for x in df.TEAMS])

In [4]:
def teamCode(S):
    
    cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','OSLO','LISBON','PARIS','BRUSSELS','ATHENS','STOCKHOLM',
          'COPENHAGEN','VIENNA', 'ANKARA','EDINBURGH','BERN']

    catsRev=[]
    for tm in S:
        if tm == cats[0]:
            catsRev.append(1)
        elif tm == cats[1]:
            catsRev.append(2)
        elif tm == cats[2]:
            catsRev.append(3)
        elif tm == cats[3]:
            catsRev.append(4)
        elif tm == cats[4]:
            catsRev.append(5)
        elif tm == cats[5]:
            catsRev.append(6)
        elif tm == cats[6]:
            catsRev.append(7)
        elif tm == cats[7]:
            catsRev.append(8)
        elif tm == cats[8]:
            catsRev.append(9)
        elif tm == cats[9]:
            catsRev.append(10)
        elif tm == cats[10]:
            catsRev.append(11)
        elif tm == cats[11]:
            catsRev.append(12)
        elif tm == cats[12]:
            catsRev.append(13)
        elif tm == cats[13]:
            catsRev.append(14)
        elif tm == cats[14]:
            catsRev.append(15)
        elif tm == cats[15]:
            catsRev.append(16)
    return catsRev

In [8]:
dfR['TEAMS']

#split TEAMS into HOME & AWAY 
dfR['HOME']=pd.Series([x.split()[1] for x in dfR.TEAMS])
dfR['AWAY']=pd.Series([x.split()[4] for x in dfR.TEAMS])
dfR['TIMED']=pd.Series([x.split()[1] for x in dfR.TIMER])
#Use teamCode FX to code HOME & AWAY collumns and crean new HOMECODE & AWAYCODE
#for t in dfR['HOME']:
dfR['AWAY']

dfR['HOMECODE']=teamCode(dfR['HOME'])
dfR['AWAYCODE']=teamCode(dfR['AWAY'])
#dfR['CODESUM']=teamCode(dfR['HOME']) + teamCode(dfR['AWAY'])
#teamCode(dfR['HOME'])

colum=['TEAMS', 'HOME','AWAY', 'HOMECODE', 'AWAYCODE', 'HTR', 'FTR', 'TIMER','TIMED']
dfR1 = dfR.reindex(columns=colum).fillna(0)#.values
# split into input (X) and output (Y) variables
dfR1

,TEAMS,HOME,AWAY,HOMECODE,AWAYCODE,HTR,FTR,TIMER,TIMED
0,VFL COPENHAGEN - VFL LONDON,COPENHAGEN,LONDON,12,4,0:0,0:1,21/07/18 03:24,03:24
1,VFL LISBON - VFL BERLIN,LISBON,BERLIN,7,3,2:0,3:2,21/07/18 03:24,03:24
2,VFL VIENNA - VFL OSLO,VIENNA,OSLO,13,6,0:1,0:3,21/07/18 03:24,03:24
3,VFL AMSTERDAM - VFL ANKARA,AMSTERDAM,ANKARA,2,14,3:0,6:0,21/07/18 03:24,03:24
4,VFL ATHENS - VFL ROME,ATHENS,ROME,10,5,1:2,1:3,21/07/18 03:24,03:24
5,VFL STOCKHOLM - VFL MADRID,STOCKHOLM,MADRID,11,1,4:0,4:1,21/07/18 03:24,03:24
6,VFL BRUSSELS - VFL PARIS,BRUSSELS,PARIS,9,8,1:1,1:1,21/07/18 03:24,03:24
7,VFL BERN - VFL EDINBURGH,BERN,EDINBURGH,16,15,0:0,1:0,21/07/18 03:24,03:24
8,VFL BERLIN - VFL BRUSSELS,BERLIN,BRUSSELS,3,9,1:0,2:0,21/07/18 03:29,03:29
9,VFL PARIS - VFL BERN,PARIS,BERN,8,16,0:0,0:2,21/07/18 03:29,03:29
10,VFL LONDON - VFL STOCKHOLM,LONDON,STOCKHOLM,4,11,2:0,5:1,21/07/18 03:29,03:29
11,VFL ROME - VFL COPENHAGEN,ROME,COPENHAGEN,5,12,2:2,4:2,21/07/18 03:29,03:29
12,VFL OSLO - VFL LISBON,OSLO,LISBON,6,7,0:0,1:1,21/07/18 03:29,03:29
13,VFL ANKARA - VFL ATHENS,ANKARA,ATHENS,14,10,3:0,3:1,21/07/18 03:29,03:29
14,VFL EDINBURGH - VFL AMSTERDAM,EDINBURGH,AMSTERDAM,15,2,0:2,0:3,21/07/18 03:29,03:29
15,VFL MADRID - VFL VIENNA,MADRID,VIENNA,1,13,2:1,3:1,21/07/18 03:29,03:29
16,VFL ATHENS - VFL EDINBURGH,ATHENS,EDINBURGH,10,15,0:3,3:3,21/07/18 03:33,03:33
17,VFL AMSTERDAM - VFL PARIS,AMSTERDAM,PARIS,2,8,1:0,3:0,21/07/18 03:33,03:33
18,VFL LONDON - VFL MADRID,LONDON,MADRID,4,1,0:1,0:2,21/07/18 03:33,03:33
19,VFL BRUSSELS - VFL OSLO,BRUSSELS,OSLO,9,6,0:1,0:1,21/07/18 03:33,03:33
20,VFL COPENHAGEN - VFL ANKARA,COPENHAGEN,ANKARA,12,14,1:0,2:1,21/07/18 03:33,03:33
21,VFL STOCKHOLM - VFL ROME,STOCKHOLM,ROME,11,5,0:1,1:4,21/07/18 03:33,03:33
22,VFL BERN - VFL BERLIN,BERN,BERLIN,16,3,0:1,1:1,21/07/18 03:33,03:33
23,VFL LISBON - VFL VIENNA,LISBON,VIENNA,7,13,0:0,0:0,21/07/18 03:33,03:33
24,VFL PARIS - VFL ATHENS,PARIS,ATHENS,8,10,0:1,2:3,21/07/18 03:38,03:38
25,VFL BERLIN - VFL AMSTERDAM,BERLIN,AMSTERDAM,3,2,2:0,2:0,21/07/18 03:38,03:38
26,VFL ROME - VFL LONDON,ROME,LONDON,5,4,2:0,2:0,21/07/18 03:38,03:38
27,VFL OSLO - VFL BERN,OSLO,BERN,6,16,0:1,1:2,21/07/18 03:38,03:38
28,VFL MADRID - VFL LISBON,MADRID,LISBON,1,7,2:2,3:3,21/07/18 03:38,03:38
29,VFL VIENNA - VFL BRUSSELS,VIENNA,BRUSSELS,13,9,0:0,0:1,21/07/18 03:38,03:38
...,...,...,...,...,...,...,...,...,...
6210,VFL EDINBURGH - VFL LISBON,EDINBURGH,LISBON,15,7,0:3,0:3,18/07/18 18:38,18:38
6211,VFL PARIS - VFL BERLIN,PARIS,BERLIN,8,3,1:2,2:2,18/07/18 18:38,18:38
6212,VFL ROME - VFL COPENHAGEN,ROME,COPENHAGEN,5,12,1:0,2:1,18/07/18 18:38,18:38
6213,VFL VIENNA - VFL OSLO,VIENNA,OSLO,13,6,0:1,1:2,18/07/18 18:38,18:38
6214,VFL ANKARA - VFL MADRID,ANKARA,MADRID,14,1,1:1,2:3,18/07/18 18:38,18:38
6215,VFL BERN - VFL STOCKHOLM,BERN,STOCKHOLM,16,11,0:0,2:0,18/07/18 18:38,18:38
6216,VFL MADRID - VFL LONDON,MADRID,LONDON,1,4,0:1,2:3,18/07/18 18:43,18:43
6217,VFL ROME - VFL VIENNA,ROME,VIENNA,5,13,1:1,2:2,18/07/18 18:43,18:43
6218,VFL LISBON - VFL BERN,LISBON,BERN,7,16,0:0,1:1,18/07/18 18:43,18:43
6219,VFL OSLO - VFL PARIS,OSLO,PARIS,6,8,0:1,1:1,18/07/18 18:43,18:43
6220,VFL BRUSSELS - VFL AMSTERDAM,BRUSSELS,AMSTERDAM,9,2,0:0,0:0,18/07/18 18:43,18:43
6221,VFL COPENHAGEN - VFL STOCKHOLM,COPENHAGEN,STOCKHOLM,12,11,1:0,2:0,18/07/18 18:43,18:43
6222,VFL BERLIN - VFL ANKARA,BERLIN,ANKARA,3,14,0:0,1:0,18/07/18 18:43,18:43
6223,VFL ATHENS - VFL EDINBURGH,ATHENS,EDINBURGH,10,15,2:0,2:0,18/07/18 18:43,18:43
6224,VFL LONDON - VFL BERLIN,LONDON,BERLIN,4,3,1:1,1:2,18/07/18 18:47,18:47
6225,VFL BERN - VFL ATHENS,BERN,ATHENS,16,10,1:0,2:0,18/07/18 18:47,18:47
6226,VFL EDINBURGH - VFL BRUSSELS,EDINBURGH,BRUSSELS,15,9,1:0,3:0,18/07/18 18:47,18:47
6227,VFL ANKARA - VFL OSLO,ANKARA,OSLO,14,6,0:0,0:0,18/07/18 18:47,18:47
6228,VFL STOCKHOLM - VFL LISBON,STOCKHOLM,LISBON,11,7,2:0,2:0,18/07/18 18:47,18:47
6229,VFL AMSTERDAM - VFL MADRID,AMSTERDAM,MADRID,2,1,0:0,0:2,18/07/18 18:47,18:47
6230,VFL PARIS - VFL ROME,PARIS,ROME,8,5,0:1,0:3,18/07/18 18:47,18:47
6231,VFL VIENNA - VFL COPENHAGEN,VIENNA,COPENHAGEN,13,12,0:0,0:0,18/07/18 18:47,18:47
6232,VFL COPENHAGEN - VFL LISBON,COPENHAGEN,LISBON,12,7,0:2,0:3,18/07/18 18:52,18:52
6233,VFL ROME - VFL ANKARA,ROME,ANKARA,5,14,0:2,0:3,18/07/18 18:52,18:52
6234,VFL BERLIN - VFL AMSTERDAM,BERLIN,AMSTERDAM,3,2,0:0,0:0,18/07/18 18:52,18:52
6235,VFL ATHENS - VFL STOCKHOLM,ATHENS,STOCKHOLM,10,11,2:0,5:0,18/07/18 18:52,18:52
6236,VFL OSLO - VFL LONDON,OSLO,LONDON,6,4,1:1,2:1,18/07/18 18:52,18:52
6237,VFL VIENNA - VFL PARIS,VIENNA,PARIS,13,8,1:0,1:0,18/07/18 18:52,18:52
6238,VFL BRUSSELS - VFL BERN,BRUSSELS,BERN,9,16,0:0,0:0,18/07/18 18:52,18:52
6239,VFL MADRID - VFL EDINBURGH,MADRID,EDINBURGH,1,15,2:0,3:0,18/07/18 18:52,18:52

In [ ]:
dfR['TEAMS'].head()

#split TEAMS into HOME & AWAY 
dfR['HOME']=pd.Series([x.split()[1] for x in dfR.TEAMS])
dfR['AWAY']=pd.Series([x.split()[3] for x in dfR.TEAMS])
#Use teamCode FX to code HOME & AWAY collumns and crean new HOMECODE & AWAYCODE
#dfR['HOMECODE']=teamCode(dfR['HOME'])
#dfR['AWAYCODE']=teamCode(dfR['AWAY'])


#colum=['TEAMS', 'HOME','AWAY', 'HOMECODE', 'AWAYCODE',
#'1', '2', 'X', 'HT1', 'HT2', 'HTX', 'FS (0:0)', 'FS(0:0)2', 'FS(0:0)X',
      #  'G(0.5)O', 'G(0.5)U', 'G(1.5)O', 'G(1.5)U', 'G(2.5)O',
     #  'G(2.5)U', 'G(3.5)O', 'G(3.5)U', 'G(4.5)O', 'G(4.5)U']
dataR=dfR.fillna(0)#.values
# split into input (X) and output (Y) variables